insert into municipios (name)values('	Altamira	 - 	Puerto Plata	 ' );
insert into municipios (name)values('	Arenoso	 - 	Duarte	 ' );
insert into municipios (name)values('	Azua	 - 	Azua	 ' );
insert into municipios (name)values('	Bajos de Haina	 - 	San Cristóbal	 ' );
insert into municipios (name)values('	Baní	 - 	Peravia	 ' );
insert into municipios (name)values('	Bánica	 - 	Elías Piña	 ' );
insert into municipios (name)values('	Barahona	 - 	Barahona	 ' );
insert into municipios (name)values('	Bayaguana	 - 	Monte Plata	 ' );
insert into municipios (name)values('	Bisonó	 - 	Santiago	 ' );
insert into municipios (name)values('	Boca Chica	 - 	Santo Domingo	 ' );
insert into municipios (name)values('	Bohechío	 - 	San Juan	 ' );
insert into municipios (name)values('	Bonao	 - 	Monseñor Nouel	 ' );
insert into municipios (name)values('	Cabral	 - 	Barahona	 ' );
insert into municipios (name)values('	Cabrera	 - 	María Trinidad Sánchez	 ' );
insert into municipios (name)values('	Cambita Garabitos	 - 	San Cristóbal	 ' );
insert into municipios (name)values('	Castañuelas	 - 	Monte Cristi	 ' );
insert into municipios (name)values('	Castillo	 - 	Duarte	 ' );
insert into municipios (name)values('	Cayetano Germosén	 - 	Espaillat	 ' );
insert into municipios (name)values('	Cevicos	 - 	Sánchez Ramírez	 ' );
insert into municipios (name)values('	Comendador	 - 	Elías Piña	 ' );
insert into municipios (name)values('	Constanza	 - 	La Vega	 ' );
insert into municipios (name)values('	Consuelo	 - 	San Pedro de Macorís	 ' );
insert into municipios (name)values('	Cotuí	 - 	Sánchez Ramírez	 ' );
insert into municipios (name)values('	Cristóbal	 - 	Independencia	 ' );
insert into municipios (name)values('	Dajabón	 - 	Dajabón	 ' );
insert into municipios (name)values('	Duvergé	 - 	Independencia	 ' );
insert into municipios (name)values('	El Cercado	 - 	San Juan	 ' );
insert into municipios (name)values('	El Factor	 - 	María Trinidad Sánchez	 ' );
insert into municipios (name)values('	El Llano	 - 	Elías Piña	 ' );
insert into municipios (name)values('	El Peñón	 - 	Barahona	 ' );
insert into municipios (name)values('	El Pino	 - 	Dajabón	 ' );
insert into municipios (name)values('	El Seibo	 - 	El Seibo	 ' );
insert into municipios (name)values('	El Valle	 - 	Hato Mayor	 ' );
insert into municipios (name)values('	Enriquillo	 - 	Barahona	 ' );
insert into municipios (name)values('	Esperanza	 - 	Valverde	 ' );
insert into municipios (name)values('	Estebanía	 - 	Azua	 ' );
insert into municipios (name)values('	Eugenio María de Hostos	 - 	Duarte	 ' );
insert into municipios (name)values('	Fantino	 - 	Sánchez Ramírez	 ' );
insert into municipios (name)values('	Fundación	 - 	Barahona	 ' );
insert into municipios (name)values('	Galván	 - 	Bahoruco	 ' );
insert into municipios (name)values('	Gaspar Hernández	 - 	Espaillat	 ' );
insert into municipios (name)values('	Guananico	 - 	Puerto Plata	 ' );
insert into municipios (name)values('	Guayabal	 - 	Azua	 ' );
insert into municipios (name)values('	Guayacanes	 - 	San Pedro de Macorís	 ' );
insert into municipios (name)values('	Guaymate	 - 	La Romana	 ' );
insert into municipios (name)values('	Guayubín	 - 	Monte Cristi	 ' );
insert into municipios (name)values('	Hato Mayor	 - 	Hato Mayor	 ' );
insert into municipios (name)values('	Higüey	 - 	La Altagracia	 ' );
insert into municipios (name)values('	Hondo Valle	 - 	Elías Piña	 ' );
insert into municipios (name)values('	Imbert	 - 	Puerto Plata	 ' );
insert into municipios (name)values('	Jamao Al Norte	 - 	Espaillat	 ' );
insert into municipios (name)values('	Jánico	 - 	Santiago	 ' );
insert into municipios (name)values('	Jaquimeyes	 - 	Barahona	 ' );
insert into municipios (name)values('	Jarabacoa	 - 	La Vega	 ' );
insert into municipios (name)values('	Jima Abajo	 - 	La Vega	 ' );
insert into municipios (name)values('	Jimaní	 - 	Independencia	 ' );
insert into municipios (name)values('	Juan de Herrera	 - 	San Juan	 ' );
insert into municipios (name)values('	Juan Santiago	 - 	Elías Piña	 ' );
insert into municipios (name)values('	La Ciénaga	 - 	Barahona	 ' );
insert into municipios (name)values('	La Descubierta	 - 	Independencia	 ' );
insert into municipios (name)values('	Laguna Salada	 - 	Valverde	 ' );
insert into municipios (name)values('	La Mata	 - 	Sánchez Ramírez	 ' );
insert into municipios (name)values('	La Romana	 - 	La Romana	 ' );
insert into municipios (name)values('	Las Charcas	 - 	Azua	 ' );
insert into municipios (name)values('	Las Guáranas	 - 	Duarte	 ' );
insert into municipios (name)values('	Las Matas de Farfán	 - 	San Juan	 ' );
insert into municipios (name)values('	Las Matas de Santa Cruz	 - 	Monte Cristi	 ' );
insert into municipios (name)values('	Las Salinas	 - 	Barahona	 ' );
insert into municipios (name)values('	Las Terrenas	 - 	Samaná	 ' );
insert into municipios (name)values('	Las Yayas de Viajama	 - 	Azua	 ' );
insert into municipios (name)values('	La Vega	 - 	La Vega	 ' );
insert into municipios (name)values('	Licey al Medio	 - 	Santiago	 ' );
insert into municipios (name)values('	Loma de Cabrera	 - 	Dajabón	 ' );
insert into municipios (name)values('	Los Alcarrizos	 - 	Santo Domingo	 ' );
insert into municipios (name)values('	Los Cacaos	 - 	San Cristóbal	 ' );
insert into municipios (name)values('	Los Hidalgos	 - 	Puerto Plata	 ' );
insert into municipios (name)values('	Los Llanos	 - 	San Pedro de Macorís	 ' );
insert into municipios (name)values('	Los Ríos	 - 	Bahoruco	 ' );
insert into municipios (name)values('	Luperón	 - 	Puerto Plata	 ' );
insert into municipios (name)values('	Maimón	 - 	Monseñor Nouel	 ' );
insert into municipios (name)values('	Mao	 - 	Valverde	 ' );
insert into municipios (name)values('	Matanzas	 - 	Peravia	 ' );
insert into municipios (name)values('	Mella	 - 	Independencia	 ' );
insert into municipios (name)values('	Miches	 - 	El Seibo	 ' );
insert into municipios (name)values('	Moca	 - 	Espaillat	 ' );
insert into municipios (name)values('	Monción	 - 	Santiago Rodríguez	 ' );
insert into municipios (name)values('	Monte Cristi	 - 	Monte Cristi	 ' );
insert into municipios (name)values('	Monte Plata	 - 	Monte Plata	 ' );
insert into municipios (name)values('	Nagua	 - 	María Trinidad Sánchez	 ' );
insert into municipios (name)values('	Neiba	 - 	Bahoruco	 ' );
insert into municipios (name)values('	Nizao	 - 	Peravia	 ' );
insert into municipios (name)values('	Oviedo	 - 	Pedernales	 ' );
insert into municipios (name)values('	Padre Las Casas	 - 	Azua	 ' );
insert into municipios (name)values('	Paraíso	 - 	Barahona	 ' );
insert into municipios (name)values('	Partido	 - 	Dajabón	 ' );
insert into municipios (name)values('	Pedernales	 - 	Pedernales	 ' );
insert into municipios (name)values('	Pedro Brand	 - 	Santo Domingo	 ' );
insert into municipios (name)values('	Pedro Santana	 - 	Elías Piña	 ' );
insert into municipios (name)values('	Pepillo Salcedo	 - 	Monte Cristi	 ' );
insert into municipios (name)values('	Peralta	 - 	Azua	 ' );
insert into municipios (name)values('	Peralvillo	 - 	Monte Plata	 ' );
insert into municipios (name)values('	Piedra Blanca	 - 	Monseñor Nouel	 ' );
insert into municipios (name)values('	Pimentel	 - 	Duarte	 ' );
insert into municipios (name)values('	Polo	 - 	Barahona	 ' );
insert into municipios (name)values('	Postrer Río	 - 	Independencia	 ' );
insert into municipios (name)values('	Pueblo Viejo	 - 	Azua	 ' );
insert into municipios (name)values('	Puerto Plata	 - 	Puerto Plata	 ' );
insert into municipios (name)values('	Puñal	 - 	Santiago	 ' );
insert into municipios (name)values('	Quisqueya	 - 	San Pedro de Macorís	 ' );
insert into municipios (name)values('	Ramón Santana	 - 	San Pedro de Macorís	 ' );
insert into municipios (name)values('	Rancho Arriba	 - 	San José de Ocoa	 ' );
insert into municipios (name)values('	Restauración	 - 	Dajabón	 ' );
insert into municipios (name)values('	Río San Juan	 - 	María Trinidad Sánchez	 ' );
insert into municipios (name)values('	Sabana de la Mar	 - 	Hato Mayor	 ' );
insert into municipios (name)values('	Sabana Grande de Boyá	 - 	Monte Plata	 ' );
insert into municipios (name)values('	Sabana Grande de Palenque	 - 	San Cristóbal	 ' );
insert into municipios (name)values('	Sabana Iglesia	 - 	Santiago	 ' );
insert into municipios (name)values('	Sabana Larga	 - 	San José de Ocoa	 ' );
insert into municipios (name)values('	Sabana Yegua	 - 	Azua	 ' );
insert into municipios (name)values('	Salcedo	 - 	Hermanas Mirabal	 ' );
insert into municipios (name)values('	Samaná	 - 	Samaná	 ' );
insert into municipios (name)values('	San Antonio de Guerra	 - 	Santo Domingo	 ' );
insert into municipios (name)values('	Sánchez	 - 	Samaná	 ' );
insert into municipios (name)values('	San Cristóbal	 - 	San Cristóbal	 ' );
insert into municipios (name)values('	San Francisco de Macorís	 - 	Duarte	 ' );
insert into municipios (name)values('	San Gregorio de Nigua	 - 	San Cristóbal	 ' );
insert into municipios (name)values('	San Ignacio de Sabaneta	 - 	Santiago Rodríguez	 ' );
insert into municipios (name)values('	San José de Las Matas	 - 	Santiago	 ' );
insert into municipios (name)values('	San José de Ocoa	 - 	San José de Ocoa	 ' );
insert into municipios (name)values('	San Juan	 - 	San Juan	 ' );
insert into municipios (name)values('	San Pedro de Macorís	 - 	San Pedro de Macorís	 ' );
insert into municipios (name)values('	San Rafael del Yuma	 - 	La Altagracia	 ' );
insert into municipios (name)values('	Santiago de los Caballeros	 - 	Santiago	 ' );
insert into municipios (name)values('	Santo Domingo Este	 - 	Santo Domingo	 ' );
insert into municipios (name)values('	Santo Domingo Norte	 - 	Santo Domingo	 ' );
insert into municipios (name)values('	Santo Domingo Oeste	 - 	Santo Domingo	 ' );
insert into municipios (name)values('	Sosúa	 - 	Puerto Plata	 ' );
insert into municipios (name)values('	Tábara Arriba	 - 	Azua	 ' );
insert into municipios (name)values('	Tamayo	 - 	Bahoruco	 ' );
insert into municipios (name)values('	Tamboril	 - 	Santiago	 ' );
insert into municipios (name)values('	Tenares	 - 	Hermanas Mirabal	 ' );
insert into municipios (name)values('	Vallejuelo	 - 	San Juan	 ' );
insert into municipios (name)values('	Vicente Noble	 - 	Barahona	 ' );
insert into municipios (name)values('	Villa Altagracia	 - 	San Cristóbal	 ' );
insert into municipios (name)values('	Villa González	 - 	Santiago	 ' );
insert into municipios (name)values('	Villa Hermosa	 - 	La Romana	 ' );
insert into municipios (name)values('	Villa Isabela	 - 	Puerto Plata	 ' );
insert into municipios (name)values('	Villa Jaragua	 - 	Bahoruco	 ' );
insert into municipios (name)values('	Villa Los Almácigos	 - 	Santiago Rodríguez	 ' );
insert into municipios (name)values('	Villa Montellano	 - 	Puerto Plata	 ' );
insert into municipios (name)values('	Villa Riva	 - 	Duarte	 ' );
insert into municipios (name)values('	Villa Tapia	 - 	Hermanas Mirabal	 ' );
insert into municipios (name)values('	Villa Vásquez	 - 	Monte Cristi	 ' );
insert into municipios (name)values('	Yaguate	 - 	San Cristóbal	 ' );
insert into municipios (name)values('	Yamasá	 - 	Monte Plata	 ' );
